environment:
  nodejs_version: '11'
  GH_TOKEN:
    secure: iF9O6+0EP1bpkx/6WURZbhtIRDQEzFw8F9Saim8lL22aNl3jUiS+MiQHTmkFvjh2

init:
  - ps: Install-Product node $env:nodejs_version

cache:
  - node_modules

install:
  - yarn install

build_script:
  - yarn build

deploy_script:
  - yarn dist
