environment:
  nodejs_version: "11"

init:
  - ps: Install-Product node $env:nodejs_version

cache:
  - node_modules

install:
  - yarn install

build_script:
  - yarn build

deploy_script:
  - yarn dist
