os:
  - linux
  - windows

dist: xenial

addons:
  apt:
    update: true
    packages:
      - bsdtar
      - build-essential
      - g++-multilib
      - gcc-multilib
      - libopenjp2-tools
      - python
      - rpm
      - snapcraft

language: node_js
node_js:
  - "11"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn build
  - yarn dist
