matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env: TARGET_OS=macos
    - os: linux
      services: docker
      env: TARGET_OS=windows
    - os: linux
      env: TARGET_OS=linux

language: node_js
node_js:
  - '10'

addons:
  apt:
    update: true
    packages:
      - libssl-dev

before_install:
  # macos
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s /usr/local/opt/openssl/include/openssl /usr/local/include ; fi

install:
  - yarn install
  - curl -u AquiGorka:$GITHUB_PAT https://api.github.com/user
  - curl https://api.github.com/rate_limit
  - yarn add @textile/go-textile-dep

script:
  # windows
  - if [ "$TARGET_OS" == "windows" ]; then echo env ; fi
  - |
    if [ "$TARGET_OS" == "windows" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        electronuserland/builder:wine \
        /bin/bash -c "yarn && yarn exec electron-builder install-app-deps && yarn build && yarn dist --windows"
    fi
  # linux and macos
  - if [ "$TARGET_OS" != "windows" ]; then yarn exec electron-builder install-app-deps ; fi
  - if [ "$TARGET_OS" != "windows" ]; then yarn build ; fi
  - if [ "$TARGET_OS" != "windows" ]; then yarn dist --$TARGET_OS ; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_PAT
  file_glob: true
  file:
    - 'dist/Permaweb-*.AppImage'
    - 'dist/Permaweb-*.exe'
    - 'dist/Permaweb-*.dmg'
  on:
    tags: true
