os:
  - linux
  - windows

dist: xenial

addons:
  apt:
    update: true
    packages:
      - bsdtar
      - build-essential
      - g++-multilib
      - gcc-multilib
      - libopenjp2-tools
      - python
      - rpm
      - snapcraft

language: node_js
node_js:
  - "11"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install openssl.light --params "/InstallDir:C:\OpenSSL-Win64\" ; fi

install:
  - yarn install

script:
  - yarn build
  - yarn dist
